export const categories = [
    {
        title: "Drip Lateral Pipe",
        img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/BO/LC/RE/84812035/product-jpeg-250x250.jpg",
        subs: [
            "Inline Drip Lateral Pipe", "Online Drip Lateral Pipe", "Black Inline Drip Irrigation Pipes"
        ],
    },
    {
        title: "Drip Irrigation Pipe",
        img: "https://5.imimg.com/data5/SELLER/Default/2023/7/325998938/VG/DP/MR/84812035/drip-irrigation-pipes-250x250.jpg",
        subs: [
            "Drip Irrigation Pipes", "Drip Irrigation Tube", "LDPE Agriculture Pipe"
        ],
    },
    {
        title: "LDPE Granules",
        img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/SM/MG/SL/84812035/product-jpeg-250x250.jpg",
        subs: [
            "Natural LDPE Granules Double 60 Filter 6", "Black LDPE Plastic Granules"
        ],
    },
    {
        title: "Lateral Pipe",
        img: "https://5.imimg.com/data5/SELLER/Default/2023/7/325998143/OF/SO/AW/84812035/online-drip-lateral-250x250.jpg",
        subs: [
            "Online Drip Lateral Pipe"
        ],
    },
]

export const abouts = [
    {
        question: "Nature of Business",
        answer: "Manufacturer"
    },
    {
        question: "Number Of Employees",
        answer: "40-50"
    },
    {
        question: "Year Of Establishment",
        answer: "2020"
    },
    {
        question: "Legal Status of Firm",
        answer: "Individual-Proprietor"
    },
    {
        question: "Annual Turnover",
        answer: "Rs. 50 Lakh to 1 Crore"
    },
    {
        question: "GST Number",
        answer: "27AOBPM1537R1ZI"
    },


    //     //Payment Mode
    // Online/ RTGS/ NEFT/ cheque/ Cash
    // 
    // 

]

export const products = [
    {
        id: 1,
        title: "Inline Drip Lateral",
        img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/BO/LC/RE/84812035/product-jpeg-250x250.jpg",
        category: categories[0].title,
        price: "1200/Roll",
        brand: "Mesh Irrigation",
        length: "500 m",
        thickness: "0.6 mm",
        Material: "LDPE",
        color: "Black",
        min_qty: "100 Rolls",
        quantity: false,
        size: false,
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 2,
        title: "Online Drip Lateral",
        img: "https://5.imimg.com/data5/SELLER/Default/2020/12/JH/QE/MR/84812035/online-drip-lateral-pipe-500x500.jpg",
        category: categories[0].title,
        price: "1100/Roll",
        brand: "Mesh Irrigation",
        length: false,
        thickness: "0.6 mm",
        Material: false,
        color: "Black",
        min_qty: "100 Rolls",
        quantity: "11 Kg",
        size: false,
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 3,
        title: "Black Inline Drip Irrigation Pipes",
        img: "https://5.imimg.com/data5/SELLER/Default/2020/12/IR/QH/UL/84812035/black-inline-drip-irrigation-pipes-500x500.jpg",
        category: categories[0].title,
        price: "1100/Roll",
        brand: "Mesh Irrigation",
        length: "300 m",
        thickness: "0.6 mm",
        Material: "LDPE",
        color: "Black",
        min_qty: "100 Rolls",
        quantity: "11 Kg",
        size: "16 mm",
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 4,
        title: "Mesh irrigation Online Drip Lateral Pipe",
        img: "https://5.imimg.com/data5/SELLER/Default/2020/12/LQ/ST/ZJ/84812035/new-product-1--500x500.jpg",
        category: categories[0].title,
        price: "1300/Roll",
        brand: "Mesh Irrigation",
        length: "500 m",
        thickness: "0.9 mm",
        Material: "LDPE",
        color: "Black",
        min_qty: "50 Rolls",
        quantity: "13 Kg",
        size: "12 mm",
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 5,
        title: "Mesh Flat Inline Drip Lateral 16 MM",
        img: "https://5.imimg.com/data5/SELLER/Default/2022/2/JM/VO/IJ/84812035/mesh-irigation-inline-drip-lateral-pipe-500x500.jpg",
        category: categories[0].title,
        price: "1600/Roll",
        brand: "Mesh Irrigation",
        length: "500 m",
        thickness: "0.5 mm",
        Material: "LDPE",
        color: "Black",
        min_qty: "50 Rolls",
        quantity: "10 Kg",
        size: "16 mm",
        drip_emitter: "Inline",
        shape: "Circle",
        drip_spacing: 40,
        model_ame: false,
        area: "Any",
        process_types: "Automatic",
        flow_rate: 4,
        dripper_spacing: 40,
        wall_thickness: 0.5,
        discharge_pressure: 4,
        iso: "Non ISI Certified",
        deal: "New Only",
        country: "India",

    },
    {
        id: 6,
        title: "Online Drip Lateral",
        img: "https://5.imimg.com/data5/SELLER/Default/2022/2/QW/SY/EH/84812035/online-drip-lateral-500x500.jpg",
        category: categories[0].title,
        price: "1100/Roll",
        brand: "Mesh Agro",
        length: "300+",
        thickness: "0.6 mm",
        Material: "LLDPE",
        color: "Black",
        min_qty: "100 Rolls",
        quantity: false,
        size: "12 mm",
        drip_emitter: "Inline",
        shape: "Round",
        drip_spacing: "40 mm",
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 7,
        title: "Drip Irrigation Pipes",
        img: "https://5.imimg.com/data5/SELLER/Default/2023/7/325998938/VG/DP/MR/84812035/drip-irrigation-pipes-500x500.jpg",
        category: categories[1].title,
        price: "1300/Roll",
        brand: "Mesh Irrigation",
        length: "500, 300/500",
        thickness: "2 mm",
        Material: "LDPE",
        color: "Black",
        min_qty: "50 Rolls",
        quantity: false,
        size: "16 mm",
        drip_emitter: false,
        shape: "Round",
        working_pressure: "4 Kg/Sqcm",
        pipe_joint: "Ring Fit / Push Fit",
        drip_spacing: false,
        model_ame: false,
        area: "2 Acre, Any, 4 Acre",
        process_types: "Semi Automatic, Manual",
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 8,
        title: "Drip Irrigation Tube",
        img: "https://5.imimg.com/data5/SELLER/Default/2022/2/ZW/YJ/KV/84812035/mesh-flat-inline-drip-lateral-16mm-500x500.jpg",
        category: categories[1].title,
        price: "110 / Piece",
        brand: "Mesh Irrigation",
        length: "500 m",
        pressure: "5 Bar",
        thickness: "0.6 mm",
        Material: "LLDPE",
        color: "Black",
        min_qty: "10 Pieces",
        quantity: false,
        size: "6 mm",
        drip_emitter: false,
        shape: "Cylindrical",
        automatic_grade: "Semi Automatic",
        drip_spacing: "30 cm",
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 9,
        title: "LDPE Agricultural Pipe",
        img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/LQ/QZ/JE/84812035/product-jpeg-500x500.jpg",
        category: categories[1].title,
        price: "Not Given",
        brand: "Mesh Agro industries",
        length: "6 m",
        thickness: "0.6mm",
        Material: "LDPE",
        material_grade: "PE 100",
        pressure_ratting: "PN 6",
        usage: "Agricultural Water Supply",
        color: "Black",
        min_qty: false,
        quantity: false,
        size: "2 inch",
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 10,
        title: "Natural LDPE Granules Double 60 Filter 6",
        img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/SM/MG/SL/84812035/product-jpeg-500x500.jpg",
        category: categories[2].title,
        price: "80/Kg",
        brand: "Mesh Irrigation",
        length: false,
        usage: "Plastic Industry",
        packaging_type: "Bag",
        packaging_size: "25 Kg",
        thickness: false,
        Material: "LDPE",
        color: "Natural",
        min_qty: "2000 Kg",
        quantity: false,
        size: false,
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 11,
        title: "Black LDPE Plastic Granules",
        img: "https://5.imimg.com/data5/SELLER/Default/2020/12/US/VO/GL/84812035/new-product-500x500.jpeg",
        category: categories[2].title,
        price: "75/Kg",
        brand: "Mesh Irrigation",
        packaging_type: "Bag",
        packaging_size: "25 Kg",
        length: false,
        thickness: false,
        Material: "LDPE",
        color: "Black",
        min_qty: false,
        quantity: false,
        size: false,
        drip_emitter: false,
        shape: false,
        drip_spacing: false,
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
    {
        id: 12,
        title: "Online Drip Lateral",
        img: "https://5.imimg.com/data5/ANDROID/Default/2023/1/TG/AE/KE/84812035/product-jpeg-500x500.jpg",
        category: categories[3].title,
        price: "1200/Roll",
        brand: "Mesh Irrigation",
        length: "400 m",
        thickness: "2 mm",
        Material: "LDPE",
        color: "Black",
        min_qty: "50 Rolls",
        quantity: false,
        size: "20 mm",
        drip_emitter: "Outline",
        working_pressure: "4 Kg/Sqcm",
        pipe_joint: "Ring Fit / Push Fit",
        shape: false,
        drip_spacing: "20 cm",
        model_ame: false,
        area: false,
        process_types: false,
        flow_rate: false,
        dripper_spacing: false,
        wall_thickness: false,
        discharge_pressure: false,
        iso: false,
        deal: false,
        country: "India",

    },
]

